### ISSUE TITLE
version upgrade issue

### ISSUE THREAD

**Issue by AndreyGrand** [ZhangMYihua/lesson-6#27]
tested for lesson-5 and lesson-6
after 
yarn install
yarn start
have next error:
./src/pages/homepage/homepage.styles.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/pages/homepage/homepage.styles.scss)
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
after 
yarn upgrade 
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\HomeProject\complete-react-developer-zero-to-mastery\lesson-6\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Users\\andre\\AppData\\Local\\Volta\\tools\\image\\node\\14.17.1\\node.exe" "C:\\HomeProject\\complete-react-developer-zero-to-mastery\\lesson-6\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\HomeProject\complete-react-developer-zero-to-mastery\lesson-6\node_modules\node-sass
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
yarn start
 react-scripts start
Starting the development server...
Failed to compile.
./node_modules/react-error-overlay/lib/index.js
Error: Cannot find module '@babel/helper-regex'

**Comment by shaoor1994** [comment]
While I was coding till video 83 I found  error with react router dom for using switch and  with route Can you please help me fix it? I am  posting error below: 


Compiled with problems:X

ERROR in ./src/App.js 14:35-41

export 'Switch' (imported as 'Switch') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, NavigationType, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createPath, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, parsePath, renderMatches, resolvePath, unstable_HistoryRouter, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams)


ERROR in ./src/components/menu-item/menu-item.component.jsx 60:21-31

export 'withRouter' (imported as 'withRouter') was not found in 'react-router-dom' (possible exports: BrowserRouter, HashRouter, Link, MemoryRouter, NavLink, Navigate, NavigationType, Outlet, Route, Router, Routes, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, createPath, createRoutesFromChildren, createSearchParams, generatePath, matchPath, matchRoutes, parsePath, renderMatches, resolvePath, unstable_HistoryRouter, useHref, useInRouterContext, useLinkClickHandler, useLocation, useMatch, useNavigate, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams)
![image](https://user-images.githubusercontent.com/59144234/156937538-86d0582b-6931-4da8-9e96-3e9c5681eaa4.png)
